# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

genOMat <- function(num_rows, num_cols) {
    .Call(`_fastshap_genOMat`, num_rows, num_cols)
}

genFrankensteinMatrices <- function(X, W, O, feature) {
    .Call(`_fastshap_genFrankensteinMatrices`, X, W, O, feature)
}

